### PR TITLE
Add salt into FarmFingerprinter.

### PR DESCRIPTION
**Pull request by renjiezh**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch-java/18)

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch-java/18)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @ple13 and @SanjayVas)

___
*[`src/main/java/org/wfanet/anysketch/SketchProtos.java` line 121 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch-java/18#-NikPefODDYEaLCASIfF:-NikbioOAusi1c2uXiDa:bd3vbr7) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch-java/blob/25d2ced4d032e4c6e295217ec3e72ffe3261a4d9/src/main/java/org/wfanet/anysketch/SketchProtos.java#L121)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This is confusing. You get a SaltedFingerpinter when the salt is empty? Intuitively it would be the other way around.

We should also be very clear if there's different behavior when no salt is specified, e.g. if they wouldn't get the same output from `FarmFingerprinter("")`
</blockquote></details>

Thanks for the point. 
I added some comments to explain the reason of legacy code.

**Review by ple13 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch-java/18)* status: 5 of 6 files reviewed, 2 unresolved discussions (waiting on @renjiezh and @SanjayVas)

___
*[`src/main/java/org/wfanet/anysketch/SketchProtos.java` line 121 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch-java/18#-NikPefODDYEaLCASIfF:-NikcdDXDkJyy5SuWIdR:b-9qlyht) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch-java/blob/25d2ced4d032e4c6e295217ec3e72ffe3261a4d9/src/main/java/org/wfanet/anysketch/SketchProtos.java#L121)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

Thanks for the point. 
I added some comments to explain the reason of legacy code.
</blockquote></details>

It looks like `name` is used as a `salt` in the legacy code (https://github.com/world-federation-of-advertisers/any-sketch-java/blob/00d8c349aa9acf28f0c21ad66bc2182aca141328/src/main/java/org/wfanet/anysketch/fingerprinters/SaltedFingerprinter.java#L21). Should we change `name` to `salt` instead of having a new argument?
___
*[`src/main/java/org/wfanet/anysketch/SketchProtos.java` line 127 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch-java/18#-Nike2G2-2Yt6BeHOwTg:-Nike2G2-2Yt6BeHOwTh:bsk4vod) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch-java/blob/c9f850eb33c07491824cf2d641105fca18059e6a/src/main/java/org/wfanet/anysketch/SketchProtos.java#L127)):*
> ```Java
>       return new SaltedFingerprinter(name, new FarmFingerprinter());
>     }
>     return new FarmFingerprinter(salt);
> ```

I couldn't find the FarmFingerprinter constructor that takes a string as an argument. It seems like FarmFingerprinter(salt) is no different than FarmFingerprinter()?

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch-java/18)* status: 5 of 6 files reviewed, 2 unresolved discussions (waiting on @ple13 and @SanjayVas)

___
*[`src/main/java/org/wfanet/anysketch/SketchProtos.java` line 121 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch-java/18#-NikPefODDYEaLCASIfF:-NikkmHx4k_XqoRjPHAI:b-udkk9q) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch-java/blob/25d2ced4d032e4c6e295217ec3e72ffe3261a4d9/src/main/java/org/wfanet/anysketch/SketchProtos.java#L121)):*
<details><summary><i>Previously, ple13 (Phi) wrote…</i></summary><blockquote>

It looks like `name` is used as a `salt` in the legacy code (https://github.com/world-federation-of-advertisers/any-sketch-java/blob/00d8c349aa9acf28f0c21ad66bc2182aca141328/src/main/java/org/wfanet/anysketch/fingerprinters/SaltedFingerprinter.java#L21). Should we change `name` to `salt` instead of having a new argument?
</blockquote></details>

The `SaltedFingerprinter` was using salt by `String.format("AnySketchFingerprint:%s:%s", item, salt)`. But new `FarmhashFingerprinter` are using it like `$item$salt`. We need a way to differentiate them to be compatible.
___
*[`src/main/java/org/wfanet/anysketch/SketchProtos.java` line 127 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch-java/18#-Nike2G2-2Yt6BeHOwTg:-Nikm2p_9WXrjUPfgu29:b-csbbfa) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch-java/blob/c9f850eb33c07491824cf2d641105fca18059e6a/src/main/java/org/wfanet/anysketch/SketchProtos.java#L127)):*
<details><summary><i>Previously, ple13 (Phi) wrote…</i></summary><blockquote>

I couldn't find the FarmFingerprinter constructor that takes a string as an argument. It seems like FarmFingerprinter(salt) is no different than FarmFingerprinter()?
</blockquote></details>

Here is the constructors.
https://github.com/world-federation-of-advertisers/any-sketch-java/pull/18/files#diff-f443c88f96caec5d31904bccebdd41fb535204bf81d01bc999f068120f40c310R29-R35

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch-java/18)* status: 5 of 6 files reviewed, 2 unresolved discussions (waiting on @ple13 and @renjiezh)

___
*[`src/main/java/org/wfanet/anysketch/SketchProtos.java` line 121 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch-java/18#-NikPefODDYEaLCASIfF:-NikvUMf2ViscBMIKOdn:bwq0hoh) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch-java/blob/25d2ced4d032e4c6e295217ec3e72ffe3261a4d9/src/main/java/org/wfanet/anysketch/SketchProtos.java#L121)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

The `SaltedFingerprinter` was using salt by `String.format("AnySketchFingerprint:%s:%s", item, salt)`. But new `FarmhashFingerprinter` are using it like `$item$salt`. We need a way to differentiate them to be compatible.
</blockquote></details>

Due to behavioral differences, let's make empty string explicitly different from no salt.

1. Update the protobuf definitions to add the `optional` keyword to the `salt` fields.
2. Have two overloads here, one which has a salt and one which doesn't.

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch-java/18)* status: 4 of 6 files reviewed, 2 unresolved discussions (waiting on @ple13 and @SanjayVas)

___
*[`src/main/java/org/wfanet/anysketch/SketchProtos.java` line 121 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch-java/18#-NikPefODDYEaLCASIfF:-NilA67f5VLVym0cspcw:bdrz43y) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch-java/blob/25d2ced4d032e4c6e295217ec3e72ffe3261a4d9/src/main/java/org/wfanet/anysketch/SketchProtos.java#L121)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Due to behavioral differences, let's make empty string explicitly different from no salt.

1. Update the protobuf definitions to add the `optional` keyword to the `salt` fields.
2. Have two overloads here, one which has a salt and one which doesn't.
</blockquote></details>

Done.
Added `optional` in proto. The two overloads take the same parameter list, so I renamed one a bit.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch-java/18)* status: all files reviewed, 2 unresolved discussions (waiting on @ple13 and @renjiezh)

___
*[`src/main/java/org/wfanet/anysketch/SketchProtos.java` line 122 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch-java/18#-NilcjBz4X4OKcrQxbMe:-NilcjC-0RL_pmcynG1X:b-vfpdeg) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch-java/blob/20120deb537165b8650c8875254dca0b0344d308/src/main/java/org/wfanet/anysketch/SketchProtos.java#L122)):*
> ```Java
>   }
> 
>   // This is for backward compatibility. When customized salt is not specified, use previous
> ```

Use JavaDoc syntax for methods.

**Review by ple13 — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch-java/18)* status: all files reviewed, 1 unresolved discussion (waiting on @renjiezh)

**Review by stevenwarejones — COMMENTED** [review]
> Reviewed 2 of 6 files at r1, 1 of 2 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch-java/18)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @renjiezh)

___
*[`src/test/java/org/wfanet/anysketch/testdata/salted_liquid_legions.textpb` line 7 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch-java/18#-NitdYIq5BpUqAFuYqN4:-NitdYIr1sQCwfNzSG7F:b-k2y2ds) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch-java/blob/ef38562a66e6e83834d46a4820e98afeafead7a6/src/test/java/org/wfanet/anysketch/testdata/salted_liquid_legions.textpb#L7)):*
> ```
>       rate: 23.0
>       num_values: 330000
>       salt: "salt"
> ```

is this intended to be a shared salt among all EDPs?

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch-java/18)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @SanjayVas and @stevenwarejones)

___
*[`src/main/java/org/wfanet/anysketch/SketchProtos.java` line 122 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch-java/18#-NilcjBz4X4OKcrQxbMe:-NiuDGTQArvC0QFT4UO-:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch-java/blob/20120deb537165b8650c8875254dca0b0344d308/src/main/java/org/wfanet/anysketch/SketchProtos.java#L122)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Use JavaDoc syntax for methods.
</blockquote></details>

Done.
___
*[`src/test/java/org/wfanet/anysketch/testdata/salted_liquid_legions.textpb` line 7 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch-java/18#-NitdYIq5BpUqAFuYqN4:-NiuDEw12m2lIKUmSnjm:bb77ufg) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch-java/blob/ef38562a66e6e83834d46a4820e98afeafead7a6/src/test/java/org/wfanet/anysketch/testdata/salted_liquid_legions.textpb#L7)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

is this intended to be a shared salt among all EDPs?
</blockquote></details>

Yes.

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 2 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch-java/18)* status: all files reviewed, 2 unresolved discussions (waiting on @SanjayVas)

**Review by renjiezh — COMMENTED** [review]
> Reviewed 4 of 6 files at r1, 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> Dismissed @SanjayVas and @stevenwarejones from 2 discussions.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch-java/18)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

**Pull request merged**
