### PR TITLE
Migrate to Bzlmod.

### PR DESCRIPTION
**Pull request by SanjayVas**
This updates Bazel to 6.4.0.

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch-java/19)

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch-java/19)* status: 0 of 23 files reviewed, all discussions resolved (waiting on @YuhongWang-Amazon)

___
*[`.bazelrc` line 15 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch-java/19#-NoxDMto4MRwMczLFOSD:-NoxDMtp2wrgifaN2gWM:b-ajnlff) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch-java/blob/70b681ce21ae2b0ec7a5c5c8821d8a3755b88b8e/.bazelrc#L15)):*
> ```
> build --java_runtime_version=remotejdk_11
> 
> # Target Java language version 9.
> ```

Newer compilers brought in by this change give warnings of Java 8 being deprecated and dropped in a future release.

**Review by YuhongWang-Amazon — APPROVED** [review]
> Reviewed 23 of 23 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch-java/19)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`MODULE.bazel` line 32 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch-java/19#-NoxRLoZCKEcdLRqXMQh:-NoxRLoZCKEcdLRqXMQi:b-2lahm2) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch-java/blob/70b681ce21ae2b0ec7a5c5c8821d8a3755b88b8e/MODULE.bazel#L32)):*
> ```Starlark
>     name = "any-sketch",
>     version = "0.6.0",
>     repo_name = "any_sketch",
> ```

It is nice that there is no more need to calculate the sha256. :)

**Review by SanjayVas — COMMENTED** [review]
> Dismissed @YuhongWang-Amazon from a discussion.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch-java/19)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Pull request merged**
