### PR TITLE
Update common-cpp to v0.10.0

### PR DESCRIPTION
**Pull request by renjiezh**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch-java/15)

**Review by SanjayVas — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch-java/15)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @iverson52000 and @renjiezh)

___
*[`WORKSPACE` line 43 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch-java/15#-NUYQ5t9-ETpq09IDLOd:-NUYQ5t9-ETpq09IDLOe:b4s72di) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch-java/blob/7c21eefc0311ee64307aeb2c19f800dbdcfb873c/WORKSPACE#L43)):*
> ```Starlark
>     sha256 = "a30369e28ae3788356b734239559f3d0c035d9121963ab00a797615364d4f0c4",
>     version = "0.3.0",
> )
> ```

nit: update this to use a version of any-sketch that has the same common-cpp dep



_Code quote:_
```Starlark
wfa_repo_archive(
    name = "any_sketch",
    repo = "any-sketch",
    sha256 = "a30369e28ae3788356b734239559f3d0c035d9121963ab00a797615364d4f0c4",
    version = "0.3.0",
)
```

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch-java/15)* status: all files reviewed, 1 unresolved discussion (waiting on @iverson52000 and @renjiezh)

**Review by Marco-Premier — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch-java/15)* status: all files reviewed, 1 unresolved discussion (waiting on @iverson52000, @renjiezh, and @stevenwarejones)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch-java/15)* status: all files reviewed, 1 unresolved discussion (waiting on @iverson52000 and @renjiezh)

**Pull request merged**
