### PR TITLE
Add JNI for secret share generator adapter.

### PR DESCRIPTION
**Pull request by ple13**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch-java/21)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 6 of 7 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch-java/21)* status: all files reviewed, 2 unresolved discussions (waiting on @ple13 and @renjiezh)

___
*[`src/main/java/org/wfanet/frequencycount/secret_share_generator.swig` line 19 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch-java/21#-NtrVmz-5_sA7vL1Vmvn:-NtrVmz-5_sA7vL1Vmvo:b9eueto) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch-java/blob/18d2d48a4ea475296191a7d81a7bcfd7a5be8ecc/src/main/java/org/wfanet/frequencycount/secret_share_generator.swig#L19)):*
> ```
> #include "frequency_count/secret_share_generator_adapter.h"
> %}
> ```

Ensure that generated Java functions follow Java naming rules (lowerCamelCase instead of UpperCamelCase). A quick search showed the syntax for this is likely

```swig
%rename("%(lowercamelcase)s",%$isfunction) "";
```

but I don't really know SWIG so I'm not certain
___
*[`src/test/java/org/wfanet/frequencycount/SecretShareGeneratorTest.java` line 37 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch-java/21#-NtrWtJR42yGaQOOYcvO:-NtrWtJS-ZUkEydSD2ia:b-pfkw1b) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch-java/blob/18d2d48a4ea475296191a7d81a7bcfd7a5be8ecc/src/test/java/org/wfanet/frequencycount/SecretShareGeneratorTest.java#L37)):*
> ```Java
> 
>   @Test
>   public void SecretShareGenerator_emptyFrequencyVectorShouldThrow() {
> ```

nit: the test naming pattern here should be the same as in Kotlin, only using underscores instead of spaces



_Suggestion:_
```Java
generateSecretShares_throws_whenFrequencyVectorEmpty
```

**Review by ple13 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch-java/21)* status: all files reviewed, 1 unresolved discussion (waiting on @renjiezh and @SanjayVas)

___
*[`src/main/java/org/wfanet/frequencycount/secret_share_generator.swig` line 19 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch-java/21#-NtrVmz-5_sA7vL1Vmvn:-NttWai68A4P08MY8Fgt:b-p9ce1r) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch-java/blob/18d2d48a4ea475296191a7d81a7bcfd7a5be8ecc/src/main/java/org/wfanet/frequencycount/secret_share_generator.swig#L19)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Ensure that generated Java functions follow Java naming rules (lowerCamelCase instead of UpperCamelCase). A quick search showed the syntax for this is likely

```swig
%rename("%(lowercamelcase)s",%$isfunction) "";
```

but I don't really know SWIG so I'm not certain
</blockquote></details>

Thanks. This is used in another swig file as well.
___
*[`src/test/java/org/wfanet/frequencycount/SecretShareGeneratorTest.java` line 37 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch-java/21#-NtrWtJR42yGaQOOYcvO:-NttXGPM53fYYjQ0tkej:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch-java/blob/18d2d48a4ea475296191a7d81a7bcfd7a5be8ecc/src/test/java/org/wfanet/frequencycount/SecretShareGeneratorTest.java#L37)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: the test naming pattern here should be the same as in Kotlin, only using underscores instead of spaces
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch-java/21)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ple13)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 3 of 7 files at r1, 1 of 1 files at r2, 1 of 2 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch-java/21)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Marco-Premier)

**Review by Marco-Premier — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch-java/21)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ple13)

**Pull request merged**
